#include <iostream>
#include <string>
#include <vector>
#include <iomanip>
#include <sstream>
#include <cstdint>

using namespace std;

typedef uint32_t uint32;
typedef uint64_t uint64;

// Left rotate
inline uint32 leftRotate(uint32 value, size_t bits) {
    return (value << bits) | (value >> (32 - bits));
}

class SHA1 {
public:
    static string calculate(const string &input) {
        // Initial hash values
        uint32 h0 = 0x67452301;
        uint32 h1 = 0xEFCDAB89;
        uint32 h2 = 0x98BADCFE;
        uint32 h3 = 0x10325476;
        uint32 h4 = 0xC3D2E1F0;

        // Convert input to bytes
        vector<uint8_t> msg(input.begin(), input.end());

        uint64 original_len_bits = msg.size() * 8;

        // Append '1' bit
        msg.push_back(0x80);

        // Pad with zeros
        while ((msg.size() * 8) % 512 != 448) {
            msg.push_back(0x00);
        }

        // Append original length
        for (int i = 7; i >= 0; i--) {
            msg.push_back((original_len_bits >> (i * 8)) & 0xFF);
        }

        // Process chunks
        for (size_t i = 0; i < msg.size(); i += 64) {
            uint32 w[80];

            // First 16 words
            for (int j = 0; j < 16; j++) {
                w[j] = (msg[i + j * 4] << 24) |
                       (msg[i + j * 4 + 1] << 16) |
                       (msg[i + j * 4 + 2] << 8) |
                       (msg[i + j * 4 + 3]);
            }

            // Extend to 80 words
            for (int j = 16; j < 80; j++) {
                w[j] = leftRotate(w[j - 3] ^ w[j - 8] ^ w[j - 14] ^ w[j - 16], 1);
            }

            uint32 a = h0, b = h1, c = h2, d = h3, e = h4;

            // Main loop
            for (int j = 0; j < 80; j++) {
                uint32 f, k;

                if (j < 20) {
                    f = (b & c) | ((~b) & d);
                    k = 0x5A827999;
                } else if (j < 40) {
                    f = b ^ c ^ d;
                    k = 0x6ED9EBA1;
                } else if (j < 60) {
                    f = (b & c) | (b & d) | (c & d);
                    k = 0x8F1BBCDC;
                } else {
                    f = b ^ c ^ d;
                    k = 0xCA62C1D6;
                }

                uint32 temp = leftRotate(a, 5) + f + e + k + w[j];
                e = d;
                d = c;
                c = leftRotate(b, 30);
                b = a;
                a = temp;
            }

            // Add to hash
            h0 += a;
            h1 += b;
            h2 += c;
            h3 += d;
            h4 += e;
        }

        // Convert to hex string
        stringstream ss;
        ss << hex << setfill('0');
        ss << setw(8) << h0
           << setw(8) << h1
           << setw(8) << h2
           << setw(8) << h3
           << setw(8) << h4;

        return ss.str();
    }
};

int main() {
    cout<<"Name: Khushbu Jain"<<endl;
    cout<<"Roll Number: 23115047"<<endl;

    cout << "HashCode Generated by SHA-1 for:\n";

    string s1 = "Khushbu Jain";
    cout << s1 << " : " << SHA1::calculate(s1) << endl;

    string s2 = "23115047";
    cout << s2 << " : " << SHA1::calculate(s2) << endl;

    return 0;
}
/*
Name: Khushbu Jain
Roll Number: 23115047
HashCode Generated by SHA-1 for:
Khushbu Jain : c3fb4cd34ce4a764357450e2c157922a2e61a69b
23115047 : bcf8a0f5a0e81c2a36f2e144e806a82209b242bf
*/